### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/emacs-lisp#158]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/emacs-lisp/issues/149)
- [x] [Add key features](https://github.com/exercism/emacs-lisp/issues/150)
- [x] [Add tags](https://github.com/exercism/emacs-lisp/issues/151)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/emacs-lisp/issues/152)
- [x] [Update status of track](https://github.com/exercism/emacs-lisp/issues/156)
- [x] [Update status of Concept Exercises](https://github.com/exercism/emacs-lisp/issues/157)
- [ ] [Pass linting checks](https://github.com/exercism/emacs-lisp/issues/153)
- [x] [Build Test Runner](https://github.com/exercism/emacs-lisp/issues/154)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/emacs-lisp/issues/155) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
